# Generated by Django 3.2 on 2022-08-14 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_auto_20220814_1428'),
    ]

    operations = [
        migrations.RenameField(
            model_name='achievementcat',
            old_name='achievements',
            new_name='achievement',
        ),
    ]
